# A TOML plugin for neovim:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "neovim"
type = "cli"
[platform.linux]
archive-prefix = "nvim-linux-{arch}"
exe-path = "bin/nvim"
download-file = "nvim-linux-{arch}.tar.gz"
[platform.macos]
archive-prefix = "nvim-macos-{arch}"
exe-path = "bin/nvim"
download-file = "nvim-macos-{arch}.tar.gz"
[platform.windows]
archs = ["x86_64"]
archive-prefix = "nvim-win64"
exe-path = "bin/nvim.exe"
download-file = "nvim-win64.zip"
[install]
download-url = "https://github.com/neovim/neovim/releases/download/v{version}/{download_file}"
[install.arch]
aarch64 = "arm64"
x86_64 = "x86_64"
[install.exes.nvim]
exe-path = "bin/nvim"
primary = true
[resolve]
git-url = "https://github.com/neovim/neovim"
